version: '3.9'
include:
  - proxy.yaml
x-env_file: &env_file
  env_file:
    - .env

services:
  db:
    image: mysql:8
    restart: on-failure
#    command: "--default-authentication-plugin=mysql_native_password"
    <<: [*env_file]
    volumes:
      - /var/lib/docker/volumes/db_mysql/_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    networks:
      backend:
        ipv4_address: 172.20.0.10
  web:
    build:
      dockerfile: ./Dockerfile.python
    restart: on-failure
    <<: [*env_file]
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on: ["db"]
    networks: 
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 5000:5000